from enum import StrEnum


class ErrorCode(StrEnum):
    NO_COMPUTE_SESSION = "NO_COMPUTE_SESSION"
    COMPUTE_NOT_READY = "COMPUTE_NOT_READY"
    HQ_REQUIRES_AT_LEAST_2_GPUS = "HQ_REQUIRES_AT_LEAST_2_GPUS"
    HQ_NOT_READY = "HQ_NOT_READY"
    GPU_BECAME_BUSY = "GPU_BECAME_BUSY"
    MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
    MODEL_PROFILE_MISMATCH = "MODEL_PROFILE_MISMATCH"
    CUDA_OOM = "CUDA_OOM"
    INFERENCE_FAILED = "INFERENCE_FAILED"
    ENCODING_FAILED = "ENCODING_FAILED"
    CANCELLED_BY_USER = "CANCELLED_BY_USER"
    RUNNER_HEARTBEAT_LOST = "RUNNER_HEARTBEAT_LOST"
    ARTIFACT_WRITE_FAILED = "ARTIFACT_WRITE_FAILED"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    INVALID_ASSET = "INVALID_ASSET"


class OneiroiError(Exception):
    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
